// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDwycFN_nXev5mK76vMd2QteSrjtTFyIM',
    appId: '1:475195321019:web:aa1e3f56d187e8d01ed79e',
    messagingSenderId: '475195321019',
    projectId: 'shad1-bfc04',
    authDomain: 'shad1-bfc04.firebaseapp.com',
    storageBucket: 'shad1-bfc04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK0LR3a0tA2aWW3Ge38GGRRxZ4uN_WXAQ',
    appId: '1:475195321019:android:a26ee83fa671742d1ed79e',
    messagingSenderId: '475195321019',
    projectId: 'shad1-bfc04',
    storageBucket: 'shad1-bfc04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGN0NLKy_FaYSMV-0v2DkcfpiyeSATnIA',
    appId: '1:475195321019:ios:f254a4c0238ae0ca1ed79e',
    messagingSenderId: '475195321019',
    projectId: 'shad1-bfc04',
    storageBucket: 'shad1-bfc04.appspot.com',
    iosClientId: '475195321019-8uog4o93jebao0ug8dc71m5cctmrp0cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mustOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGN0NLKy_FaYSMV-0v2DkcfpiyeSATnIA',
    appId: '1:475195321019:ios:f254a4c0238ae0ca1ed79e',
    messagingSenderId: '475195321019',
    projectId: 'shad1-bfc04',
    storageBucket: 'shad1-bfc04.appspot.com',
    iosClientId: '475195321019-8uog4o93jebao0ug8dc71m5cctmrp0cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mustOnline',
  );
}
